# Capítulo 6: Relações Fuzzy em Python

>## Modelagem e Simulação de Sistemas Usando Lógica Fuzzy com Python: Teoria e Prática
>### Aurtor: Jorge Zavaleta

## Importando a bibliteca Numpy

In [1]:
# importando as biblitecas necessarias
import numpy as np

## Relações Fuzzy

### Relação Binária Fuzzy

Produto Cartesiano é definido como:
$R = \{((x,y),\mu_{R}(x,y))|(x,y) \in X \times Y \}$

### Matriz de Pertinância

$\begin{equation}
	\label{eq:mpertinencia}
	R = \left[
	\begin{array}{cccc}
	\mu_{R}(x_{1},y_{1}) & \mu_{R}(x_{1},y_{2}) & \cdots & \mu_{R}(x_{1},y_{n}) \\
	\mu_{R}(x_{2},y_{1}) & \mu_{R}(x_{2},y_{2}) & \cdots & \mu_{R}(x_{2},y_{n}) \\
	\vdots & \vdots & \vdots & \vdots \\
	\mu_{R}(x_{m},y_{1}) & \mu_{R}(x_{m},y_{2}) & \cdots & \mu_{R}(x_{m},y_{n})
	\end{array}
	\right]
	\end{equation}$

Observa-se que a partir da matriz de pertinência geral podem ser induzidas algumas relações especiais e suas matrizes de pertinência.

### Relação Identidade

$\begin{equation}
	\label{eq:ridentidade}
	R_{I} = \left[
	\begin{array}{cccc}
	1 & 0 & \cdots & 0 \\
	0 & 1 & \cdots & 0 \\
	\vdots & \vdots & \vdots & \vdots \\
	0 & 0 & \cdots & 1
	\end{array}
	\right]
	\end{equation}$

In [2]:
# matriz para uma Relação Fuzzy Identidade
RI = np.identity(5, dtype=float)
print('Relação Identidade RI:')
print(RI)

Relação Identidade RI:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Relação Universo

$\begin{equation}
	\label{eq:runiverso}
	R_{E} = \left[
	\begin{array}{cccc}
	1 & 1 & \cdots & 1 \\
	1 & 1 & \cdots & 1 \\
	\vdots & \vdots & \vdots & \vdots \\
	1 & 1 & \cdots & 1
	\end{array}
	\right]
	\end{equation}$

In [3]:
# Matriz universo NxN (5x5)
RU = np.ones((5,5), dtype=float)
print('Relação Universo RU:')
print(RU)

Relação Universo RU:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Relação Nula

$\begin{equation}
	\label{eq:rnula}
	R_{0} = \left[
	\begin{array}{cccc}
	0 & 0 & \cdots & 0 \\
	0 & 0 & \cdots & 0 \\
	\vdots & \vdots & \vdots & \vdots \\
	0 & 0 & \cdots & 0
	\end{array}
	\right]
	\end{equation}$

In [4]:
# Matriz universo NxN (5x5)
RN = np.zeros((5,5),dtype=float)
print('Relação Nula RN:')
print(RN)

Relação Nula RN:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Transposta de uma Relação Fuzzy

In [5]:
# definindo a matriz da relacao fuzzy
F = np.random.random((4,4))
R = F.round(decimals=1)
print('Relação R:')
print(R)

Relação R:
[[1.  0.9 0.3 0.3]
 [0.8 0.1 0.6 0. ]
 [0.  0.1 1.  0.3]
 [0.6 0.  0.6 0.5]]


In [6]:
# matriz transposta
t = R.T
print('Transposta da Relação  de R:')
print(t)

Transposta da Relação  de R:
[[1.  0.8 0.  0.6]
 [0.9 0.1 0.1 0. ]
 [0.3 0.6 1.  0.6]
 [0.3 0.  0.3 0.5]]


### Relação Inversa

$\begin{equation}
	\label{eq:rinversa}
	R^{-1} = \left[
	\begin{array}{cccc}
	\mu_{R}(x_{1},y_{1}) & \mu_{R}(x_{2},y_{1}) & \cdots & \mu_{R}(x_{m},y_{1}) \\
	\mu_{R}(x_{1},y_{1}) & \mu_{R}(x_{2},y_{2}) & \cdots & \mu_{R}(x_{m},y_{2}) \\
	\vdots & \vdots & \vdots & \vdots \\
	\mu_{R}(x_{1},y_{n}) & \mu_{R}(x_{2},y_{n}) & \cdots & \mu_{R}(x_{m},y_{n})
	\end{array}
	\right]
	\end{equation}$

In [7]:
# matriz da relação inversa R-1= R.T
MI = t
print('Relação inversa MI:')
print(t)

Relação inversa MI:
[[1.  0.8 0.  0.6]
 [0.9 0.1 0.1 0. ]
 [0.3 0.6 1.  0.6]
 [0.3 0.  0.3 0.5]]


In [8]:
# matriz inversa: (R-1)-1 = R
r = t.T
print('Inversa da Relação Inversa r:')
print(r)

Inversa da Relação Inversa r:
[[1.  0.9 0.3 0.3]
 [0.8 0.1 0.6 0. ]
 [0.  0.1 1.  0.3]
 [0.6 0.  0.6 0.5]]


Observar que: $(R^{-1})^{-1}(y,x)=R(x,y)$. Logo a matriz $r = R$.

## Operações Básicas com Relações Fuzzy

### União de Relações Fuzzy

Definição de união de relações fuzzy:
$\begin{equation}
\mu_{R_{1} \cup R_{2}}(x,y) = R_{1}(x,y) \vee R_{2}(x,y)
\end{equation}$

In [9]:
# funcao que calcula a união de relações fuzzy
def union_rf(A,B):
    (lA,cA) = A.shape
    (lB,cB) = B.shape
    if (lA == lB) and (cA == cB):
        out = np.zeros((lA,cA)) # cria uma matriz de zeros
        for i in range(lA):
            for j in range(cB):
                out[i,j] = np.maximum(A[i,j],B[i,j]) # maximo
    else:
        out = []
        print(' ops!. Matrizes de dimensões diferentes!!!')
    return out

$R_{1}=$ ''x é maior que y'' e sua matriz de pertinências 
$\begin{equation}
    R_{1}= \left[
    \begin{array}{cccc}
              0.0  &  0.0  &  0.1 	& 0.8 \\
			  0.0  &  0.8  &  0.0 	& 0.0 \\
			  0.1  &  0.8  &  1.0 	& 0.8 
		\end{array} 
        \right]
 \end{equation}$

In [10]:
# gerando a matriz da relação R1:
R1 = np.array([[0.0, 0.0,0.1,0.8],[0.0, 0.8,0.0,0.0],[0.1,0.8,1.0,0.8]])
print('Relação R1:')
print(R1)

Relação R1:
[[0.  0.  0.1 0.8]
 [0.  0.8 0.  0. ]
 [0.1 0.8 1.  0.8]]


$R_{2}=$ ''x é muito maior que y'' e sua matriz de pertinências 
$\begin{equation}
    R_{2} = \left[
    \begin{array}{cccc}
        0.4	  & 0.4  & 0.2 	& 0.1 \\
		0.5   & 0.0  & 1.0 	& 1.0 \\
	    0.5	  & 0.1	 & 0.2 	& 0.6 
		\end{array} 
        \right]
 \end{equation}$

In [11]:
# gerando a matriz da relação R2:
R2 = np.array([[0.4, 0.4,0.2,0.1],[0.5, 0.0,1.0,1.0],[0.5,0.1,0.2,0.6]])
print('Relação R2:')
print(R2)

Relação R2:
[[0.4 0.4 0.2 0.1]
 [0.5 0.  1.  1. ]
 [0.5 0.1 0.2 0.6]]


In [12]:
uR1R2 = union_rf(R1,R2)
print('União da Relação R1 e R2:')
print(uR1R2)

União da Relação R1 e R2:
[[0.4 0.4 0.2 0.8]
 [0.5 0.8 1.  1. ]
 [0.5 0.8 1.  0.8]]


### Interseção de Relações Fuzzy

Definição de interseção de relações fuzzy:
$\begin{equation}
\mu_{R_{1} \cap R_{2}}(x,y) = R_{1}(x,y) \wedge R_{2}(x,y)
\end{equation}$

In [13]:
# funcao que calcula a interseção de relações fuzzy
def intersec_rf(A,B):
    (lA,cA) = A.shape
    (lB,cB) = B.shape
    if (lA == lB) and (cA == cB):
        out = np.zeros((lA,cA)) # cria uma matriz de zeros
        for i in range(lA):
            for j in range(cB):
                out[i,j] = np.minimum(A[i,j],B[i,j]) # minimo
    else:
        out = []
        print(' ops!. Matrizes de dimensões diferentes!!!')
    return out

In [14]:
i_R1_R2 = intersec_rf(R1,R2)
print('Interseção da Relação R1 e R2:')
print(i_R1_R2)

Interseção da Relação R1 e R2:
[[0.  0.  0.1 0.1]
 [0.  0.  0.  0. ]
 [0.1 0.1 0.2 0.6]]


## Composição de Relações Fuzzy

Seja as relações fuzzy $R_{1}$ = "x é relevante para y" e $R_{2}$ = "y é relevante para z" definidas sobre $X \times Y$ e $Y \times Z$ respectivamente, onde $X = \{1,2,3\}$, $Y=\{\alpha, \beta, \gamma,\delta\}$ e $Z=\{a, b\}$. Exemplo tomado do livro de Jang \cite{Jang1997}. Assumir que $R_{1}$  e $R_{2}$ podem ser representadas como as seguintes relações matriciais:

$ R_{1} $ = $\left[
\begin{array}{cccc}
0.1 & 0.3 & 0.5 & 0.7 \\
0.4 & 0.2 & 0.8 & 0.9 \\
0.6 & 0.8 & 0.3 & 0.2
\end{array}
\right]_{3x4}$

In [15]:
# gerando a matriz de pertinencias da relacao R1:
M1 = np.array([[0.1, 0.3,0.5,0.7],[0.4, 0.2, 0.8, 0.9],[0.6, 0.8, 0.3, 0.2]])
print('Matriz de pertinências M1:')
print(M1)

Matriz de pertinências M1:
[[0.1 0.3 0.5 0.7]
 [0.4 0.2 0.8 0.9]
 [0.6 0.8 0.3 0.2]]


$ R_{2} $ = $\left[
\begin{array}{cccc}
0.9 & 0.1  \\
0.2 & 0.3 \\
0.5 & 0.6 \\
0.7 & 0.2 
\end{array}
\right]_{4x2}$

In [16]:
# gerando a matriz de pertinencias da relacao R2:
M2 = np.array([[0.9, 0.1],[0.2, 0.3],[0.5, 0.6],[0.7, 0.2]])
print('Matriz de pertinências M2:')
print(M2)

Matriz de pertinências M2:
[[0.9 0.1]
 [0.2 0.3]
 [0.5 0.6]
 [0.7 0.2]]


### Composição Max-Min

In [17]:
# implementacao do metodo max-min
def max_min(r,s):
    (rl,rc) = r.shape
    (sl,sc) = s.shape
    if rc == sl:
        out = np.zeros((rl,sc))
        for i in range(rl):
            for j in range(sc):
                minimos = []
                for k in range(sl):
                    a = r[i,k]
                    b = s[k,j]
                    minimo = np.minimum(a,b)
                    minimos.append(minimo)
                maximo = np.amax(minimos)
                out[i,j] = maximo
    else:
        out = []
        print(' ops!. verificar as dimensões das matrizes!!!')
    return out

In [18]:
mami = max_min(M1,M2)
print('Composição Max-Min:')
print(mami)

Composição Max-Min:
[[0.7 0.5]
 [0.7 0.6]
 [0.6 0.3]]


### Composião Max-Produto

In [19]:
# implementacao do metodo max-produto
def max_produto(r,s):
    (rl,rc) = r.shape
    (sl,sc) = s.shape
    if rc == sl:
        out = np.zeros((rl,sc))
        for i in range(rl):
            for j in range(sc):
                produtos = []
                for k in range(sl):
                    a = r[i,k]
                    b = s[k,j]
                    produto = a*b
                    produtos.append(produto)
                maximo = np.amax(produtos)
                out[i,j] = maximo
    else:
        out=[]
        print('ops!. verificar as dimensões das matrizes!!!')
    return out

In [20]:
# Usando o metodo max-produto
MP = max_produto(M1,M2)
print('Composição max-produto:')
print(MP)

Composição max-produto:
[[0.49 0.3 ]
 [0.63 0.48]
 [0.54 0.24]]


### Composição Max-Média

In [25]:
# implementacao do metodo max-media
def max_media(r,s):
    (rl,rc) = r.shape
    (sl,sc) = s.shape
    if rc == sl:
        out = np.zeros((rl,sc))
        for i in range(rl):
            for j in range(sc):
                medias = []
                for k in range(sl):
                    a = r[i,k]
                    b = s[k,j]
                    media = (a+b)/2
                    medias.append(media)
                maximo = np.amax(medias)
                out[i,j] = maximo
    else:
        out = []
        print('ops!. verificar as dimensões das matrizes!!!')
    return out

In [26]:
# usando o metodo max-media
MED = max_media(M1,M2)
print('Composição max-média:')
print(MED)

Composição max-média:
[[0.7  0.55]
 [0.8  0.7 ]
 [0.75 0.55]]


---
#### Copyright © Jorge Zavaleta, 2023